### PR TITLE
Changes added to the Group Microservice [GSoC period]

### PR DESCRIPTION
**Pull request by kengneruphine**
Here are the changes I added to the Group microservice
- PermittableGroupIds to group and modifying the boostrap .yml
- Modify the requestparams for groups in the group rest controller  file
- implemented the Update request for Group (PUT request)
- implemented the Update request for Group Definition (PUT request)

### CODE REVIEW

**Comment by awasum** [comment]
@kengneruphine Please Add unit tests for GroupDefinitions and UpdateGroups then I can merge this.
Also run licenseFormat to add apache license at the top of all source files.

**Comment by awasum** [comment]
Am still waiting for the unit test for group update before this can merged.

**Comment by kengneruphine** [comment]
Hello Awasum

I have updated the pull request to include the unit tests for group update
and group definition update.

Regards,
Ruphine Kengne

**Comment by awasum** [comment]
Thank you @kengneruphine

**Pull request merged**
